---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: appsmovie

outputs:
- name: package-output

run:
  path: appsmovie/ci/tasks/package.sh

